### ISSUE TITLE
Auth invalid password when using MD5 password

### ISSUE THREAD

**Issue by diwu1989** [wvanbergen/node-vertica#13]
Just hit this issue recently on Vertica Community Edition 6.0.1, fairly confident that the problem will exist with Vertica Enterprise as well.

It's easy to repro, just set authentication on server to MD5, then try to use the driver.

Workaround for now is to set vertica authentication to password.

I'll try to deal with this issue this weekend.

**Comment by andreyfomin** [comment]
It is not clear how to use ssl param at all. Got error message

Error: 140735285137408:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1487:SSL alert number 40

    at Error (native)
    at SlabBuffer.use (_tls_legacy.js:39:18)
    at CleartextStream._read (_tls_legacy.js:257:29)
    at CleartextStream.Readable.read (_stream_readable.js:348:10)
    at EncryptedStream._write (_tls_legacy.js:171:25)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at EncryptedStream.Writable.write (_stream_writable.js:247:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
